"use client";
import { FormEvent, useEffect, useState } from "react";

type Settings = { allowGuestCheckout: boolean; pricesIncludeTax: boolean; taxName: string; taxRate: number; storeName: string; hotline: string; orderEmail: string };
const defaults: Settings = { allowGuestCheckout: true, pricesIncludeTax: true, taxName: "VAT", taxRate: 10, storeName: "Thiên Nhật Minh Eco", hotline: "", orderEmail: "" };

export default function AdminSettingsPage() {
  const [settings, setSettings] = useState<Settings>(defaults); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/admin/settings").then(async (res) => { const data = await res.json(); if (!res.ok) throw new Error(data.error); setSettings({ ...defaults, ...data }); }).catch((e) => setMessage(e.message || "Không thể tải cài đặt")).finally(() => setLoading(false)); }, []);
  const update = <K extends keyof Settings>(key: K, value: Settings[K]) => setSettings((current) => ({ ...current, [key]: value }));
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); try { const res = await fetch("/api/admin/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setSettings(data); setMessage("Đã lưu cài đặt vào hệ thống."); } catch (e) { setMessage(e instanceof Error ? e.message : "Không thể lưu cài đặt"); } finally { setSaving(false); } }
  if (loading) return <div className="py-16 text-center text-on-surface-variant">Đang tải cài đặt...</div>;
  return <div className="mx-auto max-w-4xl space-y-6"><div><h1 className="text-2xl font-bold text-on-surface font-headline">Cài đặt hệ thống</h1><p className="mt-1 text-sm text-on-surface-variant">Các thay đổi được lưu trong database và áp dụng cho checkout.</p></div>{message && <div className={`rounded-xl px-4 py-3 text-sm ${message.startsWith("Đã") ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-700"}`}>{message}</div>}<form onSubmit={save} className="space-y-6"><section className="space-y-4 rounded-2xl border border-outline-variant bg-surface p-6 shadow-sm"><h2 className="border-b border-outline-variant pb-3 text-lg font-semibold">Checkout</h2><Toggle label="Cho phép mua hàng không cần đăng nhập" description="Khi tắt, khách phải đăng nhập trước khi đặt hàng." checked={settings.allowGuestCheckout} onChange={(value) => update("allowGuestCheckout", value)}/></section><section className="space-y-4 rounded-2xl border border-outline-variant bg-surface p-6 shadow-sm"><h2 className="border-b border-outline-variant pb-3 text-lg font-semibold">Thuế</h2><Toggle label="Giá sản phẩm đã bao gồm thuế" description="Nếu tắt, checkout sẽ cộng thuế theo mức bên dưới." checked={settings.pricesIncludeTax} onChange={(value) => update("pricesIncludeTax", value)}/><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Field label="Tên loại thuế" value={settings.taxName} onChange={(value) => update("taxName", value)}/><Field label="Mức thuế mặc định (%)" type="number" min="0" max="100" value={settings.taxRate} onChange={(value) => update("taxRate", Number(value))}/></div></section><section className="space-y-4 rounded-2xl border border-outline-variant bg-surface p-6 shadow-sm"><h2 className="border-b border-outline-variant pb-3 text-lg font-semibold">Thông tin cửa hàng</h2><div className="grid grid-cols-1 gap-4 md:grid-cols-2"><Field label="Tên cửa hàng" value={settings.storeName} onChange={(value) => update("storeName", value)}/><Field label="Hotline" value={settings.hotline} onChange={(value) => update("hotline", value)}/><div className="md:col-span-2"><Field label="Email nhận đơn hàng" type="email" value={settings.orderEmail} onChange={(value) => update("orderEmail", value)}/></div></div></section><div className="flex justify-end"><button disabled={saving} className="rounded-xl bg-primary px-6 py-2.5 text-sm font-semibold text-on-primary disabled:opacity-60">{saving ? "Đang lưu..." : "Lưu cài đặt"}</button></div></form></div>;
}
function Field({ label, value, onChange, type = "text", min, max }: { label: string; value: string | number; onChange: (value: string) => void; type?: string; min?: string; max?: string }) { return <label className="block text-sm font-medium text-on-surface">{label}<input type={type} min={min} max={max} required={label !== "Hotline"} value={value} onChange={(e) => onChange(e.target.value)} className="mt-1.5 w-full rounded-xl border border-outline-variant bg-surface-container-low px-4 py-2.5 text-sm focus:border-primary focus:outline-none"/></label>; }
function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-center justify-between gap-4 rounded-xl border border-outline-variant bg-surface-container-low p-4"><div><p className="text-sm font-semibold">{label}</p><p className="mt-0.5 text-xs text-on-surface-variant">{description}</p></div><input aria-label={label} type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} className="h-5 w-5 accent-primary"/></div>; }
